import React from 'react'
import {StyleSheet} from 'react-native'
import {px3dp} from "../../app/util/ScreenUtil";

const styles = StyleSheet.create({
    headerView:{
        width:px3dp(600),
        height:px3dp(190),
        backgroundColor:'#9fb5d5',
        flexDirection:'row',
        justifyContent:'center',
    },
    TDtext:{
        marginTop:px3dp(64),
        color:'#3a3330',
        fontSize:px3dp(60),
        alignItems:'center',
        flex:1.5,
    },
    add:{
        width:px3dp(64),
        height:px3dp(64),
        marginTop:px3dp(68),
        marginLeft:px3dp(43),
    },
    standaloneRowBack: {
        alignItems: 'center',
        backgroundColor:'#dbdde0',
        flexDirection: 'row',
        justifyContent:'flex-end',
    },
    backImgWhite: {
        width:px3dp(64),
        height:px3dp(64),
        marginTop:px3dp(33)
    },
    backImg2White: {
        width:px3dp(64),
        height:px3dp(64),
        marginTop:px3dp(33)
    },
    standaloneRowFront: {
        backgroundColor: '#CCC',
        width:px3dp(580),
        height:px3dp(130),
        alignSelf:'center'
    },
    editstyle:{
        width:px3dp(130),
        height:px3dp(130),
        paddingLeft:px3dp(33),
        backgroundColor:'#bbced7',
    },
    edit2style:{
        width:px3dp(130),
        height:px3dp(130),
        paddingLeft:px3dp(33),
        backgroundColor:'#d7bbc0'
    },

    mdtitlestyle:{
        width:px3dp(888),
        justifyContent:'space-between',
        flexDirection:'row'
    },
    surestyle:{
        width:px3dp(90),
        height:px3dp(90),
    },
    cancel:{
        width:px3dp(90),
        height:px3dp(90),
    },
    alertstyle:{
        width:px3dp(888),
        height:px3dp(680),
        backgroundColor:'#d4deec',
        borderRadius:px3dp(20)
    },
    alert1style:{
        width:px3dp(888),
        height:px3dp(780),
        backgroundColor:'#d4deec',
        borderRadius:px3dp(20)
    },
    iconstyle:{
        width:px3dp(64),
        height:px3dp(64),
        marginTop:px3dp(57),
        marginLeft:px3dp(94)
    },
    icon1style:{
        width:px3dp(64),
        height:px3dp(64),
        marginTop:px3dp(38),
        marginLeft:px3dp(94)
    },
    alertimage:{
        flexDirection:'row',
    },
    alert1image:{
        flexDirection:'row',
        justifyContent:'space-between',
    },
    linestyle:{
        width:px3dp(12),
        height:px3dp(74),
        backgroundColor:'#c0c0c0',
        marginLeft:px3dp(67),
        borderRadius:px3dp(6),
        marginTop:px3dp(52)
    },
    line1style:{
        width:px3dp(12),
        height:px3dp(74),
        backgroundColor:'#c0c0c0',
        marginLeft:px3dp(19),
        borderRadius:px3dp(6),
        marginTop:px3dp(38),
    },
    textStyle:{
        fontSize:px3dp(48),
        color:'#3a3330',
        marginLeft:px3dp(16),
        marginTop:px3dp(68)
    },
    text1Style:{
        fontSize:px3dp(48),
        color:'#3a3330',
        marginLeft:px3dp(16),
        marginTop:px3dp(56)
    },
    tsbtnstyle:{
        width:px3dp(100),
        height:px3dp(72),
        marginLeft:px3dp(17),
        marginTop:px3dp(53),
        borderRadius:px3dp(20),
        alignItems:'center',
        justifyContent:'center',
        alignSelf:'center'
    },
    tsbtn1style:{
        width:px3dp(100),
        height:px3dp(72),
        marginLeft:px3dp(60),
        marginTop:px3dp(53),
        borderRadius:px3dp(20),
        alignItems:'center',
        justifyContent:'center',
        alignSelf:'center'
    },
    tsbtn2style:{
        width:px3dp(100),
        height:px3dp(72),
        marginLeft:px3dp(60),
        marginTop:px3dp(53),
        borderRadius:px3dp(20),
        alignItems:'center',
        justifyContent:'center',
        alignSelf:'center'
    },
    tsbtn3style:{
        width:px3dp(100),
        height:px3dp(72),
        marginLeft:px3dp(94),
        marginTop:px3dp(30),
        borderRadius:px3dp(20),
        backgroundColor:'#456675',
        alignItems:'center',
        justifyContent:'center',
    },
    textbuttonstyle:{
        fontSize:px3dp(36),
        color:'#3a3330'
    },
    prioritylevel1:{
        width:px3dp(130),
        height:px3dp(16),
        marginLeft:px3dp(17),
        borderRadius:px3dp(6),
        marginTop:px3dp(45),
        alignItems:'center',
        justifyContent:'center',
        alignSelf:'center'
    },
    prioritylevel2:{
        width:px3dp(130),
        height:px3dp(16),
        marginLeft:px3dp(14),
        borderRadius:px3dp(6),
        marginTop:px3dp(45),
        alignItems:'center',
        justifyContent:'center',
        alignSelf:'center'
    },
    prioritylevel3:{
        width:px3dp(130),
        height:px3dp(16),
        marginLeft:px3dp(17),
        borderRadius:px3dp(6),
        marginTop:px3dp(45),
        alignItems:'center',
        justifyContent:'center',
        alignSelf:'center'
    },
    tistyle:{
        width:px3dp(690),
        height:px3dp(360),
        marginTop:px3dp(38),
        fontSize:px3dp(48),
        color:'#3a3330',
        alignSelf:'center',
        backgroundColor:'#ffffff',
    },
    edittime:{
        width:px3dp(64),
        height:px3dp(64),
        marginTop:px3dp(57),
        marginLeft:px3dp(80)
    },
    edit1time:{
        width:px3dp(64),
        height:px3dp(64),
        marginTop:px3dp(57),
        marginRight:px3dp(80)
    },
})

module.exports= {
    styles
}